export const ACTIONS = {
  // Navigation
  SET_VIEW: 'SET_VIEW',
  TOGGLE_SIDEBAR: 'TOGGLE_SIDEBAR',

  // Course setup
  SET_COURSE: 'SET_COURSE',
  SET_COURSE_MAP: 'SET_COURSE_MAP',

  // Source management
  ADD_SOURCE: 'ADD_SOURCE',
  REMOVE_SOURCE: 'REMOVE_SOURCE',
  UPDATE_SOURCE: 'UPDATE_SOURCE',

  // Pipeline
  PIPELINE_START: 'PIPELINE_START',
  PIPELINE_STEP: 'PIPELINE_STEP',
  PIPELINE_COMPLETE: 'PIPELINE_COMPLETE',
  PIPELINE_ERROR: 'PIPELINE_ERROR',
  PIPELINE_RESET: 'PIPELINE_RESET',

  // Analysis
  SET_ANALYSIS: 'SET_ANALYSIS',

  // Cards
  SET_CARDS: 'SET_CARDS',
  TOGGLE_PIN: 'TOGGLE_PIN',
  ADD_CARD_TAG: 'ADD_CARD_TAG',
  REMOVE_CARD_TAG: 'REMOVE_CARD_TAG',
  DELETE_CARD: 'DELETE_CARD',
  UPDATE_CARD: 'UPDATE_CARD',

  // Study
  SET_STUDY_MODE: 'SET_STUDY_MODE',

  // Filters
  SET_FILTER: 'SET_FILTER',
  RESET_FILTERS: 'RESET_FILTERS',

  // Persistence
  HYDRATE: 'HYDRATE',
  RESET_ALL: 'RESET_ALL',
};
